### ISSUE TITLE
Provide an example of how to include an AWS Component in a Recipe

### ISSUE THREAD

**Issue by GrahamLea** [aws-samples/amazon-ec2-image-builder-samples#9]
Hi.

I'm trying to use an AWS-provided Component (e.g. `arn:aws:imagebuilder:ap-southeast-2:aws:component/update-linux/1.0.0/1`) in a Recipe in CDK (1.77.0/Java), but I can't figure out how to do it. I've described it in a bit more depth here: https://forums.aws.amazon.com/thread.jspa?threadID=332428

The CDK docs around Image Builder are very sparse. I thought if you had an example here of how to do it in Cfn, it might help me figure out how to do it in CDK.

Cheers,

Graham.

**Comment by GrahamLea** [comment]
FWIW, I believe this is how to do it (at least, this is the Cfn that CDK spits out when I managed to get it to run `synth` without error, but I haven't tried `deploy`ing the stack yet)
```
  Recipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Components:
        - ComponentArn: arn:aws:imagebuilder:rn:aws:imagebuilder:ap-southeast-2:aws:component/update-linux/1.0.0/1:aws:component/update-linux/x.x.x
 ```
